#!/usr/bin/env python3
"""Create a typed all-image alt manifest from WordPress provenance and visual review.

Exact WordPress filename matches retain their original alt and source evidence. Assets without
WordPress alt provenance receive the approved visual-review alt from
`docs/visual-reviewed-image-alt.json`. The source distinction remains explicit in the output.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LEDGER = ROOT / 'docs/wordpress-to-astro-image-alt-ledger.json'
VISUAL_REVIEW = ROOT / 'docs/visual-reviewed-image-alt.json'
OUTPUT = ROOT / 'src/data/imageAltManifest.ts'


def esc(value: str) -> str:
    return value.replace('\\', '\\\\').replace("'", "\\'").replace('\n', ' ')


def main() -> None:
    ledger = json.loads(LEDGER.read_text(encoding='utf-8'))
    reviewed = json.loads(VISUAL_REVIEW.read_text(encoding='utf-8'))['alt_by_path']
    records = []
    missing_review = []

    for asset in ledger['assets']:
        path = asset['astro_public_path']
        if asset['mapping_status'] == 'legacy_alt_inherited' and asset['legacy_alt'].strip():
            records.append({
                'path': path,
                'alt': asset['legacy_alt'].strip(),
                'source': 'wordpress-inherited',
                'wordpress_upload_path': asset['wordpress_upload_path'],
                'wordpress_public_url': asset['wordpress_public_url'],
                'wordpress_attachment_id': asset['wordpress_attachment_id'],
                'reviewed_at': '',
            })
        elif path in reviewed and reviewed[path].strip():
            records.append({
                'path': path,
                'alt': reviewed[path].strip(),
                'source': 'visual-review',
                'wordpress_upload_path': '',
                'wordpress_public_url': '',
                'wordpress_attachment_id': '',
                'reviewed_at': reviewed.get('review_date', '2026-08-24'),
            })
        else:
            missing_review.append(path)

    if missing_review:
        raise RuntimeError('Missing approved visual alt for: ' + ', '.join(missing_review))

    records.sort(key=lambda item: item['path'])
    inherited_count = sum(1 for item in records if item['source'] == 'wordpress-inherited')
    visual_count = sum(1 for item in records if item['source'] == 'visual-review')
    lines = [
        '/**',
        ' * Generated by scripts/build-image-alt-manifest.py.',
        ' * WordPress provenance: docs/wordpress-to-astro-image-alt-ledger.json.',
        ' * Visual-review provenance: docs/visual-reviewed-image-alt.json.',
        ' * Do not hand-edit entries; regenerate after updating either source ledger.',
        ' */',
        '',
        "export type ImageAltSource = 'wordpress-inherited' | 'visual-review';",
        '',
        'export interface ImageAltRecord {',
        '  alt: string;',
        '  source: ImageAltSource;',
        '  wordpressUploadPath: string;',
        '  wordpressPublicUrl: string;',
        '  wordpressAttachmentId: string;',
        '  visuallyReviewedAt: string;',
        '}',
        '',
        'export const imageAltByPath: Record<string, ImageAltRecord> = {',
    ]
    for item in records:
        lines.extend([
            f"  '{esc(item['path'])}': {{",
            f"    alt: '{esc(item['alt'])}',",
            f"    source: '{item['source']}',",
            f"    wordpressUploadPath: '{esc(item['wordpress_upload_path'])}',",
            f"    wordpressPublicUrl: '{esc(item['wordpress_public_url'])}',",
            f"    wordpressAttachmentId: '{esc(item['wordpress_attachment_id'])}',",
            f"    visuallyReviewedAt: '{esc(item['reviewed_at'])}',",
            '  },',
        ])
    lines.extend([
        '};',
        '',
        '/** Return the approved alt text when this Astro asset has a tracked source record. */',
        'export function getImageAlt(path: string, fallback: string): string {',
        '  return imageAltByPath[path]?.alt || fallback;',
        '}',
        '',
        '/** @deprecated Use getImageAlt; retained for existing project and component templates. */',
        'export const getInheritedImageAlt = getImageAlt;',
        '',
    ])
    OUTPUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {OUTPUT.relative_to(ROOT)} with {len(records)} records: {inherited_count} WordPress, {visual_count} visual review')


if __name__ == '__main__':
    main()
